#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/cyberdesk/cyberdesk /usr/bin/cyberdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/cyberdesk.service ]; then
			rm /etc/systemd/system/cyberdesk.service /usr/lib/systemd/system/cyberdesk.service /usr/lib/systemd/user/cyberdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/cyberdesk/files/systemd/cyberdesk.service /usr/lib/systemd/system/cyberdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload cyberdesk.service: Unit cyberdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/cyberdesk.service:10: Executable path is not absolute: pkill -f "cyberdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/cyberdesk.service
		fi
		systemctl daemon-reload
		systemctl enable cyberdesk
		systemctl start cyberdesk
	fi
fi
